const ErrorTypeEnum =
{
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNAUTHENTICATED: 'UNAUTHENTICATED',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED_ERROR: 'TOKEN_EXPIRED_ERROR',
    REQUIRED: 'REQUIRED',
    BAD_REQUEST: 'BAD_REQUEST'
}

module.exports = ErrorTypeEnum